name: ATilionUtilities
version: 0.2.0
description: It adds some extra fun stuff to minecraft
author: TilionDC

main: me.tiliondc.atu.ATilionUtilities
database: false

commands:
  atu:
    desciption: General atilionUtilities command
    permission: atu.admin
    usage: Error, do '/atu help'
  sudo:
    description: Make a player do a command
    permission: atu.sudo
    usage: /sudo [player] [command]
  togglechairs:
    description: Toggles if you want to sit on stairs or not
    permission: atu.chairs
    usage: /togglechairs to toggle if you want to sit on stairs or not.
  fly:
    description: Enables/Disables flying
    permission: atu.fly
    usage: /fly [time in secounds] [playername]
  rules:
    description: Display the server rules.
    permission: atu.rules
    usage: /rules [world] to display the rules of the world.
  hat:
    desciption: Set block in hand as a hat on the head.
    permission: atu.hat
    usage: /hat to put the block in hand as a hat.
  kit:
    description: Gives a player the desired kit
    permission: atu.kit
    usage: /kit [kitname] to get the kit or only /kit to see the available kits.
  heal:
    description: Heals a player an given amount of health
    permission: atu.heal
    usage: /heal {player] [amount] to heal a player.
  feed:
    description: Feeds a player an given amount of hunger
    permission: atu.feed
    usage: /feed {player] [amount] to feed a player.
  signedit:
    description: Allows a player to edit the sign looked at by the player.
    permission: atu.signedit
    usage: /editsign <line> <text> to edit a sign. Player must be looking at the sign.

permissions:
  atu.admin:
    description: Permission for admin stuff
  atu.sudo:
    description: Permission for the sudo command. Should not be given to anyone.
  atu.kit:
    description: Permission for giving any kit to anyone. atu.kit.[kitname] for specific kits.
  atu.fly:
    description: Permission for being able to fly in survival mode.
  atu.fly.others:
    description: Permission for giving others the fly command.
  atu.chairs:
    description: Permission required to sit and toggle sitting.
  atu.chestlock:
    description: Permission to be able to lock chests.
  atu.rules:
    description: Permission to see the rules.
  atu.hat:
    description: Permission for using hats.
  atu.heal:
    description: Permission to heal player.
  atu.feed:
    description: Permission to feed player.
  atu.chatcolors:
    description: Permission for writng in chat and on signs with color.
  atu.pathblock:
    description: Permission for walking faster on paths.
  atu.elevators:
    description: Permissoin to use elevators.
  atu.signedit:
    description: Permissoin to edit Signs.
